model:
  n_layers: 3
  n_heads: 4
  hidden_dim: 256
  action_bins: 4
  seq_len: 4
  dueling: False
train:
  epochs: 3
  lr: 0.001
  batch_size: 128
  reg_weight: 1
  tau: 1e-3
  model_folder: models
  mc_returns: True

gamma: 0.99
env:
  id: halfcheetah-medium-expert-v2
  discrete_actions: False
  state_dim: 17
  action_dim: 6
  R_min: 0
  R_max: 500
  action_min: -1
  action_max: 1

dataset: data/pole_random_seq.pkl

