model:
  n_layers: 3
  n_heads: 4
  hidden_dim: 512
  action_bins: 256
  seq_len: 4
train:
  epochs: 3
  lr: 0.001
  batch_size: 128
  reg_weight: 0.25
  tau: 1e-3
  model_folder: models

gamma: 0.99
env:
  id: HalfCheetah-v1
  discrete_actions: True
  state_dim: 17
  action_dim: 6
  R_min: -6000
  R_max: 12000
  action_min: -1
  action_max: 1

dataset: data/random_seq.pkl

