model:
  n_layers: 3
  n_heads: 4
  hidden_dim: 512
  action_bins: 256
  seq_len: 4
train:
  epochs: 3
  lr: 0.001
  batch_size: 128
  reg_weight: 1
  tau: 5e-3
  model_folder: models

gamma: 0.99
env:
  id: HalfCheetah-v4
  discrete_actions: False
  state_dim: 17
  action_dim: 6
  R_min: -550
  R_max: -60
  action_min: -1
  action_max: 1

dataset: data/random_seq.pkl

